### ISSUE TITLE
Move Dispersy system tests into gumby

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/gumby#10]
There are two Dispersy system tests:
- test_overlay.py
- test_bootstrap.py

These can be moved to the gumby repository.  The associated R scripts can be moved there as well.

**Comment by NielsZeilemaker** [comment]
Why? I guess both these tests are unit-tests for dispersy right? As an added bonus they output some data which can be parsed by the r scripts.
The test_overlay even does an assert, hence is actually testing Dispersy. Moreover, I think the concept of bootstrap peers is not something gumby has to know anything about.

**Comment by boudewijn-tribler** [comment]
I'll leave the choice (where the py and its R scripts should be) to Elric.

**Comment by whirm** [comment]
I think what @boudewijn-tribler meant is that it should be converted to a gumby experiment.
