### ISSUE TITLE
Problems with GO command

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#101]
Currently the SyncServer sends a GO command to all clients ordering them to start the experiment. However, this results in two problems:
- The GO command will not arrive at all clients at the same time -> hence peers start at different times.
- Only after receiving the GO command is the scenario file parsed, causing huge differences between nodes. In one run I could see more than a 2s difference between actually starting the experiment.

Suggested changes:
- Add a timestamp to the GO command indicating when a client should start
- Before sending the vars, the scenario file should be parsed, after receiving the GO command + timestamp the tasks should be registered.

**Comment by NielsZeilemaker** [comment]
I made a change to the sync server which sends the node id earlier and parses the scenario file before sending the ready. 
This solves the parsing part of this issue. The go signal stuff still needs to be resolved.

**Comment by whirm** [comment]
you mean the sync client?

**Comment by NielsZeilemaker** [comment]
Yes,  I would add a timestamp to the go signal and use that a the clients to start.

**Comment by whirm** [comment]
Yeah, that's what I did, I'm sending the pull request now

**Comment by whirm** [comment]
@NielsZeilemaker Merge it if you like it
