### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by corpaul** [Tribler/gumby#134]
No idea what's causing this.. looks like pylint ???

http://jenkins.tribler.org/job/test_systemtap_tribler_unittests/160/console

**Comment by NielsZeilemaker** [comment]
which segfault, i can't see any in the log

**Comment by corpaul** [comment]
ERR: /home/jenkins/workspace/test_systemtap_tribler_unittests/gumby/scripts/run_nosetests_for_jenkins.sh: line 64: 31932 Segmentation fault      nice pylint --output-format=parseable --reports=y Tribler > $OUTPUT_DIR/pylint.out 2> $OUTPUT_DIR/pylint.log

**Comment by whirm** [comment]
I guess some interaction between the system installed pylint not liking being executed in our crazy venv, I would close this as wontfix as we shouldn't even be executing pylint in your experiment.
