### ISSUE TITLE
candidate_id not used in barter_clientclient.request_stat

### ISSUE THREAD

**Issue by snorberhuis** [Tribler/gumby#206]
@corpaul  showed me the method `request_stat` as an example of how to generate a single candidate in gumby for my own tests. But this method does not use a single candidate. Instead the method sends a request stat to every candidate.

I don't know what the wanted behavior is, but the parameter `candidate_id` is never used and it is not possible at the moment to sent a single request stat to a candidate using this method. It would be easily fixed by using the `candidate_id` as a key on `self.all_vars.`. The corresponding value will allow creation of the candidate in the same way as `c` is used for creation.

**Comment by snorberhuis** [comment]
I can make a simple pull request to fix it, if the current way is incorrect.

**Comment by corpaul** [comment]
I believe this was intended. will look into this tomorrow.

**Comment by corpaul** [comment]
Good catch, this wasn't intended :) (although it doesn't make much of a difference for the current experiments). If you can please make the pull request. It would be nice if we can either use a candidate_id to specify a specific candidate, and request stats from all candidates if no candidate_id is given.
