### ISSUE TITLE
Yappi not Installed on gorilla / bbq

### ISSUE THREAD

**Issue by wouterjsmit** [Tribler/gumby#234]
Not entirely Gumby related, but I get the following error log when trying to run a gumby config on either of those machines.

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/Relative_CPU_Performance/gumby/experiments/dispersy/tunnel_client_local_blind.py", line 7, in <module>
    import yappi
ImportError: No module named yappi
```

**Comment by whirm** [comment]
It's not available on Debian, so you will have to use a virtualenv for these experiments.

Just create a setup script that creates one for you and make gumby call it on the setup step.

You have inspiration for a rather crazy one in `scripts/build_virtualenv.sh` (don't use that one as it builds a whole bunch of stuff from source so we can run everything on the DAS clusters)

Even better, you could implement a generic script which creates a venv with the dependencies specified on a `requeriments.txt` file on your experiment config dir so anybody can use it.

**Comment by wouterjsmit** [comment]
Thanks, I'll go that route then
