### ISSUE TITLE
Communities should connect better with candidates during experiments

### ISSUE THREAD

**Issue by snorberhuis** [Tribler/gumby#237]
When running gumby experiments the behavior of the candidates list in a community should be more controllable. Currently, a node in the gumby experiment does not necessarily know every other node.
While this is required for a large set of experiments.

There are two problems:
1. The nodes are not introduced properly at the start of the experiment. There is some functionality that allows to introduce candidates, but these methods are not successful every time. You should be able to have an instruction in your scenario file that instructs a node to know every other node.
2. The nodes forget candidates during the experiment. This is probably due to Dispersy refreshing the list of candidates. You should be able to turn off this behavior.

An example of an experiment that fails due these problems is `experiments/multichain/multichain_synthetic.scenario`

I think I solved the second problem by overriding the `cleanup_candidates` method with a `MultiChainGumbyCommunity` and using this community in gumby experiments. But this should be implemented in a generic way in Gumby.

**Comment by whirm** [comment]
1. If they are not successful, it's either a bug on Dispersy or your system can't keep up with the amount of instances you are running. In big experiments like the AllChannel one we run in the DAS4, we progressively introduce peers on the network and let them discover eachother for a couple of minutes.
2. If dispersy discards candidates after a while and you make your experiment not discard them, then you won't be having the same behavior on the experiment than on the real world. Are we sure this is wanted?

**Comment by devos50** [comment]
I'm pretty sure this issue is not relevant anymore since we switched to IPv8 👍
