### ISSUE TITLE
Use psutil.pids() instead of psutil.get_pid_list()

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#249]
The `psutil.get_pid_list` function has been renamed a long time ago to `psutil.pids()` (see https://pypi.python.org/pypi/psutil vs https://pypi.python.org/pypi/psutil/0.5.0). This makes that we have to install an older version of `psutil`. If we rename this method in the code (there are two occurrences) we can use a more recent version of the `psutil` package.

**Comment by whirm** [comment]
If we do that, we should probably update the venv build script so it installs more recent versions of everything, otherwise gumby won't run on the DAS anymore.
