### ISSUE TITLE
Gumby terminating immediately after running the local_processguard.conf experiment on OS X

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#250]
When running the `local_processguard.conf` on OS X with the following command:

```
gumby/run.py gumby/experiments/dummy/local_processguard.conf
```

The experiment immediately exists:

```
MacBook-Pro-van-Martijn:Documents martijndevos$ gumby/run.py gumby/experiments/dummy/local_processguard.conf
INFO:ExperimentRunner:Syncing workspaces on remote head nodes...
INFO:ExperimentRunner:Great copying success!
INFO:ExperimentRunner:Running local and remote setup scripts
INFO:ExperimentRunner:Remote setup successful!
INFO:ExperimentRunner:Starting local and remote instances
INFO:ExperimentRunner:Locally running command process_guard.py -c "(yes CPU > /dev/null & find /etc /usr > /dev/null ; wait)" -t 10 -m $OUTPUT_DIR -o $OUTPUT_DIR
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Project root is: /Users/martijndevos/Documents
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: NOT activating virtualenv.
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Running process_guard.py -c "(yes CPU > /dev/null & find /etc /usr > /dev/null ; wait)" -t 10 -m /Users/martijndevos/Documents/output -o /Users/martijndevos/Documents/output
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: All child processes have died, exiting
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: TERMinating group. Still 1 process(es) running:
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT: Command:
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT:    (yes CPU > /dev/null & find /etc /usr > /dev/null ; wait)
INFO:OneShotProcessProtocol:[process_guard.py -c...] OUT:    exited with status: -15
INFO:OneShotProcessProtocol:[process_guard.py -c "(yes CPU > /dev/null & find /etc /usr > /dev/null ; wait)" -t 10 -m $OUTPUT_DIR -o $OUTPUT_DIR] exit code 0
INFO:ExperimentRunner:Syncing output data back from head nodes...
...
```

This also happens with running nosetests inside gumby so it should be fixed before unit tests are able to run on OS X.

Update: an `IOError` triggers (see #251) due to the `/proc` directory not being available on OS X. I suggest we should either use `psutil` or `sysctl(3)` to get statistics about a specific process. @whirm what do you think?

**Comment by whirm** [comment]
Does psutil provide all the stuff we need? (check proc(5))

**Comment by devos50** [comment]
I'm currently digging through the `psutil` documentation. It looks promising but there are some parameters I still have to find. `proc(5)` is not available on Darwin unfortunately.

**Comment by whirm** [comment]
@devos50 I know it's not, but I wouldn't want to lose statistics available on Linux just to support OSX. So if psutil doesn't provide all we need, we will have to thing of a way of solving that. Either way, adding support for OSs which don't  have /proc will mean a rewrite of process guard as we use that for everything (monitoring resource usage, telling when a process dies or a new one gets spawned, etc.).

**Comment by whirm** [comment]
Maybe we could just not use process guard on OSX for the time being and we can add suport for it at a later stage? The only thing we would miss is the resource usage graphs, which I think is a good compromise to have the tests running on OSX earlier.

Once we have the stuff running on Windows, OSX and Linux, we can do a process guard rewrite so it supports all three platforms.

**Comment by devos50** [comment]
@whirm I agree and there are some statistics I cannot get with `psutil` (for instance, `rchars`, `wchars`). As far as I can see, `procfs` is far more powerful and detailled than `psutil`. I've searched for a port of `procfs` for OS X but the one I've found is really outdated and probably not accurate (http://osxbook.com/book/bonus/chapter11/procfs/).

I agree with your last comment indeed. Maybe we can create a gumby configuration option, something like `USE_PROCFS`. If it is set, Gumby uses the `procfs` statistics. Else, it uses the statistics exposed by `psutil`. This way, we can support both platforms (and even Windows) and still take advantage of `procfs`.

**Comment by whirm** [comment]
Yeah, that's what I thought I remembered.

Looks cool, I don't know what the performance of this thing would be though.

**Comment by whirm** [comment]
Also, I don't know if OSX and windows support process groups, but if they don't I don't see a point in even trying to make process guard cross platform.

Let's leave this be until the tests are running.

**Comment by devos50** [comment]
OS X is supporting process groups, Windows is not (`os.setpgrp()` is failing).

Shall I create an issue for this?

Update: found https://osxfuse.github.io, appears to be the successor of MacFuse. I will try it out!

**Comment by whirm** [comment]
Sure, go ahead :)
