### ISSUE TITLE
Running Gumby on OS X and Windows

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#253]
In order to be able to run Gumby on OS X and Windows (for the unit tests of Tribler/Dispersy), some major changes are needed: 

`procfs` is not available on OS X and the port (https://github.com/osxfuse/filesystems/tree/master/filesystems-c/procfs) seems to be outdated. On Windows, we have no real good alternative for `procfs`. `psutil` is providing some tools to get statistics. So we might fallback on `psutil` if we do not have `procfs`.

Another issue is that Windows does not support process groups.

This issue is open for discussions, ideas and suggestions how to make Gumby cross-platform.

**Comment by whirm** [comment]
We need to have in mind that the output of the process guard's resource monitoring needs to be compatible with the normal one in all cases, or all the post processing scripts will break.

**Comment by brussee** [comment]
- and Android
