### ISSUE TITLE
Improving the testing infrastructure of Gumby

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#257]
Currently, there are no regression tests of the Gumby framework. These would be really helpful since I'm about to make some changes to the way Gumby starts up the unit tests (since I'm trying to run the unit tests on OS X and Windows). Also, creating tests for Gumby helps when we eventually want to support `psutil` graphs (besides the data `procfs` generates).

As a first step for this, we can run the basic experiment (`local_processguard`) and archive the screenshots. This should take very little time. After that, we could create some more sophisticated experiments.

**Comment by whirm** [comment]
Yes, it would be really nice to have proper tests, but having a mix of python, shell scripts and R doesn't make the task simple.

**Comment by devos50** [comment]
The basic `local_processguard` experiment is now running for every pull request. This will keep me (and others) from breaking at least the basic functionalities of Gumby.

**Comment by whirm** [comment]
Nice!

**Comment by qstokkink** [comment]
Now that we have unit tests, they should also be made part of the PR checks.

**Comment by devos50** [comment]
@qstokkink done, I've also added a Pylint checker 👍

**Comment by devos50** [comment]
I think this issue has been adequately addressed.
