### ISSUE TITLE
Make it easy to change/randomise the master member of each community

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#298]
This would make running experiments easier and allows us to run experiments in parallel on the same machine. Also, this makes sure that we are not joining the 'main' `AllChannel` community since this may interfere with the experiment.

**Comment by qstokkink** [comment]
Here is part of the problem solved, for a UNIQUE_ID of up to 68 bytes:

```python
@classmethod
def get_master_members(cls, dispersy):
    eccrypto = ECCrypto()
    private_bin = "".join([UNIQUE_ID[i] if i < len(UNIQUE_ID) else "0" for i in range(68)])
    eckey = eccrypto.key_from_private_bin("LibNaCLSK:" + private_bin)
    master_key = eckey.pub().key_to_bin()
    master = dispersy.get_member(public_key=master_key)
    return [master]
```

This creates a deterministic and valid dispersy community master member from an arbitrary string.

How to construct this `UNIQUE_ID` such that it is the same for all peers in the current experiment, is still an open problem (possibly use `environ['SYNC_HOST']`, `environ['SYNC_PORT']`, experiment start time, MAC addresses and/or other flavors of uniqueness).

EDIT: I implemented this into the solution of #300 : https://github.com/qstokkink/gumby/commit/1b31adfe54fd9521142fd1bebee2639a18301978
