### ISSUE TITLE
Setup readthedocs for Gumby

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#302]
We should have a readthedocs page where we bundle all information about Gumby. This should contain some basic guides i.e. how to run an experiment using Tribler and Dispersy.

**Comment by qstokkink** [comment]
I think all the documents we need for Gumby end-users are as follows (feedback welcome):

1. What does Gumby do (loading Dispersy communities, DAS5 & local deployment etc. etc.)
2. Dependencies and installing them
3. General overview of `.scenario`, `.conf` and `*_client.py` files
4. `Hello World!` example, explain output folder contents
5. In-depth `.scenario` files & tying into `*_client.py` files
6. In-depth `.conf` files

We might also need documentation for people modifying Gumby itself, but I'd consider that not as high of a priority.
