### ISSUE TITLE
Option to disable resource usage statistics

### ISSUE THREAD

**Issue by kc1212** [Tribler/gumby#322]
I didn't find the option to disable resource usage statistics, please let me know if such an options exists.

My [multi configuration job](https://jenkins.tribler.org/job/pers/job/consensus_thesis_multi_kcong/30/) generates almost 20 GB of data, but a lot of that is in`resource_usage.log`. Disabling resource usage would save a lot of disk space.

**Comment by qstokkink** [comment]
You should be able to disable this by passing `--monitor-dir ""` to `process_guard.py`.

**Comment by kc1212** [comment]
I see, so if I'm running experiments on DAS5, a workaround would be to write `-m ""` on [this line](https://github.com/kc1212/gumby/blob/devel/scripts/das4_node_run_job.sh#L71)

**Comment by qstokkink** [comment]
Yup, that should do it.
