### ISSUE TITLE
base_dispersy_module broken

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#343]
`base_dispersy_module.py` uses `config.set_mainline_dht_listen_port()` instead of `config.set_mainline_dht_port()`, this crashes Gumby.

**Comment by devos50** [comment]
I already fixed this in my implementation for the hidden seeding experiment (https://github.com/devos50/gumby/tree/payouts) but I haven't opened a PR yet.

**Comment by qstokkink** [comment]
@devos50 yes, I also have 3 PRs (1 PR, 2 branches to be precise) which include this fix now.
