### ISSUE TITLE
run_nosetests_for_jenkins.sh broken

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#347]
The latest change (dd286713f0d36c545ab5198e7fd8b08977781c98) broke https://github.com/Tribler/gumby/blob/devel/scripts/run_nosetests_for_jenkins.sh for Windows and Mac.

For some reason this line:
https://github.com/Tribler/gumby/blob/dd286713f0d36c545ab5198e7fd8b08977781c98/scripts/run_nosetests_for_jenkins.sh#L160-L161
Does not properly split the space delimited `$pids` into different `p`, but instead outputs:
```
line 161: wait: ` 24496 24498 24500 24502 24504': not a pid or valid job spec
```

**Comment by qstokkink** [comment]
The issue persists, but I can't reproduce this locally and I'm at a loss as to why the for loop doesn't work. We might have to revert dd286713f0d36c545ab5198e7fd8b08977781c98 and 0015a02d2855cd5b00aed44eea19765e68b073be.

**Comment by devos50** [comment]
I will try to reproduce it locally.

**Comment by qstokkink** [comment]
Aha! I also managed to reproduce it now. Somehow the other statements in the file make it fail somewhere.. (my standalone version of the for loop works just fine).

**Comment by devos50** [comment]
I'm also unable to reproduce this, using the following bash script: https://gist.github.com/devos50/6d6b9013a13e521a5a718ea576e7d363

I've tried it both with `sh` and `bash` but it doesn't give me the error.

**Comment by devos50** [comment]
@qstokkink can you share the script you're using?

**Comment by qstokkink** [comment]
@devos50 https://gist.github.com/qstokkink/a73d7588a4329b1f33ce831c322601ae

**Comment by qstokkink** [comment]
Alright, I fixed it (locally). It wasn't as trivial of a fix as I thought though.. https://github.com/Tribler/gumby/pull/349/commits/bc2ae208039fdac567690f6f7b626cc8a881be77
