### ISSUE TITLE
Enhancing the Scenario language and syntax

### ISSUE THREAD

**Issue by DanGraur** [Tribler/gumby#392]
Would it be a good idea to try and enhance the language used in the `.scenario` files? By this I mean if perhaps it would be possible to declare, for instance, variables: `&variable <some_variable_name>  := <some_value>`, and then use the variables within the `.scenario` file (e.g. `@0:10.71 find $<some_variable_name> {5}`)? For instance, I think this would be of great help in certain scenario files which repeatedly use the same value, but the writers of these `.scenario` files are forced to repeatedly copy-paste the same literal over and over. Not only is this tedious, but there might be the case that the author, or someone intending to make use of a `.scenario` file, will mistakenly change the value of a repeated literal, thus either modifying the file such that it becomes invalid, or the '.scenario' file remains valid, but yields unintended and inaccurate results. Here are several examples of files where variables might be useful: [example1](https://github.com/Tribler/gumby/blob/devel/experiments/dht/dht_experiment.local.scenario) (`value_to_store` can become a variable) and [example2](https://github.com/DanGraur/gumby/blob/dht_dissemination_experiment/experiments/dht/dht_propag_time.local.scenario) (`10d00d55231921911991e2f7fd538ec989a2df00` may become a variable).

Additionally, it might be nice to add support for loops over a single command: `@0:10 for $i in 0 to 10 [by 2] do enable_dht_store_callback 10d00d55231921911991e2f7fd538ec989a2df00 {$i}` or something of the sorts. The square brackets here (that is, `[` and `]`) represent some optional part that the `.scenario` file writer might choose to add. This might be good in the case of the 2nd example presented above (i.e. [this one](https://github.com/DanGraur/gumby/blob/dht_dissemination_experiment/experiments/dht/dht_propag_time.local.scenario)), and I'm sure many other experiments as well. I think currently the parser interprets the `.scenario` file line-by-line, without taking into consideration the nearby or even adjacent lines, thus multi-line `for`s would not work without making some more extensive changes (for instance using a Lexical Analyzer followed by a Syntactic Analyzer, which could replace the existing module used for this). That being said, a single-line `for` like the one described above could probably be implemented without much effort.   

Obviously, this will require some discussion and the actual syntax to be implemented should be settled on beforehand. Above, I've written only a simple proposal on how it might be implemented.

**Comment by qstokkink** [comment]
I think we run the risk of making the "language" overly complex.

Instead we should probably support `get` and `set` functions by default, maybe something like this:

```
@0:3 set variable_name 5
@0:4 for variable_name 1 5
 ...
@1:3 experiment_callback $(variable_name)
```

**Comment by DanGraur** [comment]
Sure, that sounds like a good compromise! 

I do have a few questions to get a better idea of the changes `here:

1. `@0:3 set variable_name 5` would set the variable called `variable_name` to `5`, `3` seconds into the experiment? I think this is pretty obvious, but I'm asking this just for the sake of a sanity check on my side.
1.  `@0:4 for variable_name 1 5` I'm a bit confused regarding the semantics of this line. Does it mean that the variable `variable_name` will be assigned the array `[1, 2, 3, 4, 5]`, which will then be passed as a parameter to the `experiment callback`? Or does it mean that (all) the next lines will be executed once for the value `1`, then once for the value `2`, etc? Or does it mean that _only_ the commands which make use of `variable_name` will be executed (in this case) 5 times, each time with a different value for `variable_name`?

Thank you!

**Comment by qstokkink** [comment]
> 1. @0:3 set variable_name 5 would set the variable called variable_name to 5, 3 seconds into the experiment?

Yes.

> 2. @0:4 for variable_name 1 5 I'm a bit confused regarding the semantics of this line.

Good point. We may want to change it a bit to something like:

```
@0:4 for variable_name in 1, 2, 3, 4, 5 call experiment_callback
@0:4 for variable_name in 1 through 5 call experiment_callback
```

The for loop is your most dangerous suggestion in my opinion. We should make sure not to start designing an entirely new Turing-complete language on top of Python 😃. Scenarios should be simple DSLs.

**Comment by DanGraur** [comment]
I completely agree that it should be kept as simple as possible, but I think these two additions might prove useful in the future. Also regarding these two options above, I think the latter: `@0:4 for variable_name in 1 through 5 call experiment_callback` is more concise and requires the same amount of writing effort for an array between `1` and `100` as it does for an array between `1` and `5`, for instance, so I think it's better than the former.

If you would like, I can try to implement these two additions. I don't expect the implementation to take too long.

**Comment by qstokkink** [comment]
Cool. I'll assign you to the issue.

**Comment by DanGraur** [comment]
Sounds good, thanks!

**Comment by synctext** [comment]
Agree with compromise. Simple minimal DSL for the win..

**Comment by DanGraur** [comment]
I've addressed half of this issue (the part referring to declaring and using variables) in PR #397. I've decided to keep them separate, since after looking into these issues more closely, I realized that the addition of the `for` for `.scenario` files will require a more extensive set of modifications, which might be suitable for a different PR.

**Comment by DanGraur** [comment]
The second part of this issue, namely the `for` loop has been address in PR #407. There's still some more functionality that can be added to the `for` loop, and especially its `peerspec`, however, I think the current implementation adds the fundamental functionality of the `for` loop, as discussed here.

**Comment by devos50** [comment]
I think this issue is sufficiently addressed?

**Comment by qstokkink** [comment]
Agreed.
