### ISSUE TITLE
Propagate stderr immediately

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/gumby#43]
Currently the process guard will collect all stdout and stderr for each process.  The resulting files can be shown once the experiment is finished.

We can improve this by passing along the stderr immediately.  The output will be collected by prun, giving feedback while the experiment is running.

**Comment by whirm** [comment]
@NielsZeilemaker are you interested in having this?

**Comment by NielsZeilemaker** [comment]
Not at all
