### ISSUE TITLE
Refactor the argument of get_peer to int

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#444]
Currently, the `get_peer` method in the `IPv8OverlayExperimentModule` class takes a string to indicate the ID of a specific peer. This is most likely because the keys in the `all_vars` dict are of type `str`. It would be more convenient to refactor this argument to an integer.

**Comment by qstokkink** [comment]
Maybe we can make a `PeerID` object that has the IP-address, Gumby ID and public key all in one convenient location?

**Comment by devos50** [comment]
We could make a subclass of `Peer` for this and add the Gumby ID?

**Comment by qstokkink** [comment]
Even better.
