### ISSUE TITLE
Make it easier to spawn multiple nodes locally

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#461]
Currently, if you want to spawn multiple Gumby nodes locally, you need the following in your configuration file:

```
local_instance_cmd = "process_guard.py -c launch_scenario.py -c launch_scenario.py -c launch_scenario.py -c launch_scenario.py -c launch_scenario.py -t $EXPERIMENT_TIME -m $OUTPUT_DIR  -o $OUTPUT_DIR "
```

This is not very pretty when one wants to run many nodes (e.g., hundreds) locally.

**Comment by devos50** [comment]
One solution could be to pass the launch command in one argument (e.g., `-c`), and make another argument for the number of instances that one wants to spawn (e.g., `-n`).

**Comment by qstokkink** [comment]
The `-n` option is already taken, but this should simply be a case of adding an integer parameter and multiplying the `commands` list by it, after..

https://github.com/Tribler/gumby/blob/c304a6a82cfb6bc9b435fd3bf507cf259d045517/gumby/process_guard.py#L370-L378

..add..

`commands = commands * repetitions`
