### ISSUE TITLE
Das4 #processes not flexible

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#49]
I want to run 4023 processes on 20 nodes. This isn't possible due to being required to choose a number of nodes (20) and a number of processes per node (201.15).

Can we switch to a number of nodes + number of processes thingy and drop the not flexible number of processes per node requirement.

**Comment by whirm** [comment]
check out proces_conf_flexibility (with typo included) works for me, if it works for you merge the pull request ;)
