### ISSUE TITLE
The isolated community launcher is setting the `master_peer` variable instead of `community_id`

### ISSUE THREAD

**Issue by devos50** [Tribler/gumby#495]
The isolated community launcher is setting the `master_peer` variable of the community instead of the `community_id` variable. This makes the current isolated community launcher useless.

**Comment by qstokkink** [comment]
https://github.com/Tribler/gumby/blob/2fc22b7275337611785ff9b4a97dcc69ff29b650/gumby/modules/isolated_community_loader.py#L55

Should be replaced with:

```python
overlay.community_id = master_peer.mid
```

**Comment by devos50** [comment]
@qstokkink Yes, working on it 😄
