### ISSUE TITLE
Dispersy errors not in stderr

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#50]
Even though the exception was logged with the ERROR level, it did not show up in stderr.

2013-10-29 11:59:10+0100 [-] ERROR   1383044350.34        callback:214   reassessing as fatal exception, attempting proper shutdown

**Comment by boudewijn-tribler** [comment]
Is this using the latest devel?  Since commit 91cb359 Dispersy is no longer configuring the logger itself (unless tool/main.py is used).  It Gumby importing the library before configuring the logger?

**Comment by NielsZeilemaker** [comment]
No clue, i'm branching of your private-search branch as that was the most up to date version upon i'm building.

I think because it's actually reporting with the ERROR prefix it's a gumby error and not a dispersy one.
Hence the ticket in gumby and not in Dispersy.

Btw, it's not a 2x configuration problem as I am actually seeing this line in the stdout file. Calling the configuration twice disables any output.

**Comment by boudewijn-tribler** [comment]
The private-search branch you are referring to does not yet have commit 91cb359, so it is configuring itself (both the basicConfig and the fileConfig).

I am not sure if it will solve the problem, but I can cherry pick 91cb359 and push it to private-search if you believe it would be helpful.

**Comment by NielsZeilemaker** [comment]
It will not, this is a gumby problem not a Dispersy problem.

**Comment by whirm** [comment]
@NielsZeilemaker check out if my "logging" branch works for you

**Comment by NielsZeilemaker** [comment]
Did you test/verify it yourself?

**Comment by whirm** [comment]
It was working fine with my dummy tests, do you have any problem with you experiment?
