### ISSUE TITLE
Argument passing

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#51]
I want to pass a json document to a method using a scenario file.
However, because the json document contains spaces gumby will split it up and pass it as separate arguments, e.g. I'm getting this error: add_friend() takes exactly 3 arguments (14 given).

Can we agree upon a "this is a single argument" delimiter in order to pass such an argument?

**Comment by whirm** [comment]
I'm splitting the args with shlex now, so we should be able to use double quotes, escaping, etc.

Could you merge whirm/gumby/scenario_argument_parsing into your branch and tell me if its OK? don't be afraid about the setup script upgrade, it won't take long at all to run.

If it's OK ill merge to master

**Comment by NielsZeilemaker** [comment]
I'll cherry-pick and test it tomorrow
