### ISSUE TITLE
Gumby does not work at DAS4 vu cluster

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#53]
Seeing this error:

python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

http://jenkins.tribler.org/job/Experiment_PrivateSocial_gumby/47/console

**Comment by corpaul** [comment]
FYI this link gives 404

**Comment by NielsZeilemaker** [comment]
Sorry for that, it must have been my muscle memory automatically removing failed builds.
You have to trust me on the error then.

**Comment by whirm** [comment]
Is this still happening? 
if it is: are you running the up to date setup script?

**Comment by NielsZeilemaker** [comment]
I guess it's fixed since we fixed the venv script. I'm running on the vu right now -> it seems to be working :+1:
