### ISSUE TITLE
Spawned processes are never killed

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#56]
After running a single gumby experiment some processes are never killed.

E.g.
/bin/bash -xe /var/scratch/zeilemak/gumby/scripts/run_tracker.sh
python -O -c from Tribler.dispersy.tool.tracker import main; main() --port 7788

**Comment by NielsZeilemaker** [comment]
Seems to be fixed with https://github.com/NielsZeilemaker/gumby/commit/1dcba62c7c621815e3456dab819cb4678e3cf16a

**Comment by NielsZeilemaker** [comment]
Patch isn't working

**Comment by whirm** [comment]
We now create a process group when starting the experiment and, after the reactor is stopped, we will scan for stray process and kill them before exiting (even if killed with SIGTERM)
