### ISSUE TITLE
Inject configuration variables through jenkins

### ISSUE THREAD

**Issue by corpaul** [Tribler/gumby#70]
I would like to be able to inject config vars for gumby through jenkins.. now I have to push the config file to git every time I want to make a small change to an experiment.

I tried using the 'inject env vars' config option in jenkins but those vars are overwritten by gumby.

**Comment by whirm** [comment]
just export the variable you want to override prefixed with GUMBY_ before starting the experiment (see gumby/settings.py:96 onwards)

It's not documented yet but the feature is there :)
