### ISSUE TITLE
VSize seems incorrect, or maybe we need to track a different memory stat

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/gumby#75]
![vsize graph](http://jenkins.tribler.org/job/GH_Tribler_pull-request-tester_devel/409/artifact/tribler/output//vsizes.png)

I really don't think tribler is using +/- 4GB

**Comment by whirm** [comment]
@NielsZeilemaker you fixed this, right?

**Comment by NielsZeilemaker** [comment]
jup, its using rss instead
