### ISSUE TITLE
gumby default config for experiment

### ISSUE THREAD

**Issue by corpaul** [Tribler/gumby#79]
It would be nice to have a mechanism in gumby which automatically checks if an experiment config variable is set and if not defaults it to a value from another config file (e.g. one that is read-only).

Now I do something like 
[ -z "$EXPERIMENT_TIME" ] && EXPERIMENT_TIME=30
but if EXPERIMENT_TIME is used in local_setup_cmd, local_instance_cmd and tracker_cmd this has to be repeated everywhere.

Also it would result in much clearer documentation.

**Comment by whirm** [comment]
Yeah, I was thinking on adding an include directive. 
But for the time being just add it to the config file and document the config option as mandatory.

**Comment by devos50** [comment]
Closing this issue since it's not relevant anymore.
